import type { Metadata } from "next";
import Link from "next/link";
import { Check, ShieldCheck, Sparkles } from "lucide-react";
import { PublicPage } from "@/components/public/PublicPage";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";

export const metadata: Metadata = {
  title: "Access — Scrooner",
  description: "Every Scrooner feature is free during beta — no credit card, no trial countdown. Here's what's included now, and how pricing will eventually work.",
};

const included = [
  "Plain-English screener across 18 locked fundamental metrics",
  "Full company pages — statements, ratios, ownership & insider activity",
  "Every number traces to its source SEC filing and formula version",
  "Save and rerun your own screens",
  "SEC EDGAR coverage across 5,000+ US-listed companies",
];

const principles = [
  {
    title: "Free core, always",
    body: "The underlying SEC data is free and redistributable by design. That stays true no matter what you pay, forever.",
  },
  {
    title: "No dark patterns",
    body: "No expiring trial, no surprise charge, no feature that quietly disappears. You'll get clear notice before anything ever requires payment.",
  },
  {
    title: "Deterministic first, AI second",
    body: "Screening results are computed from reported filings, never generated by AI. That doesn't change at any price.",
  },
];

export default function Page() {
  return (
    <PublicPage current="pricing" eyebrow="Access" title="Free while Scrooner is in beta." description="No credit card, no trial countdown, no feature held back. Everything below is live today.">
      <section>
        <h2>What you get today</h2>
        <ul className="pricing-included">{included.map((item) => <li key={item}><Check size={18} aria-hidden="true" />{item}</li>)}</ul>
        <div className="pricing-cta">
          <Button asChild size="large"><Link href="/signup">Create a free account</Link></Button>
          <Button asChild size="large" variant="ghost"><Link href="/app/screens/new">Explore the screener</Link></Button>
        </div>
      </section>

      <section>
        <h2>What premium will look like</h2>
        <div className="pricing-plans">
          <div className="pricing-plan pricing-plan--highlight">
            <div className="pricing-plan__name">Free<Badge tone="positive">Live now</Badge></div>
            <div className="pricing-plan__price"><strong>$0</strong></div>
            <p className="pricing-plan__desc">Everything listed above. No time limit, no card required.</p>
            <ul className="pricing-plan__list">
              <li><Check size={16} aria-hidden="true" />Full screener &amp; company pages</li>
              <li><Check size={16} aria-hidden="true" />Ownership &amp; insider data</li>
              <li><Check size={16} aria-hidden="true" />Saved screens</li>
            </ul>
            <Button asChild variant="secondary"><Link href="/signup">Create free account</Link></Button>
          </div>
          <div className="pricing-plan">
            <div className="pricing-plan__name">Premium<Badge>In development</Badge></div>
            <div className="pricing-plan__price"><strong>~$100</strong><span>/ year, target</span></div>
            <p className="pricing-plan__desc">We&apos;re validating one premium tier for investors who want to go deeper. The exact scope and price aren&apos;t locked yet — shown here so there are no surprises later.</p>
            <ul className="pricing-plan__list">
              <li><Sparkles size={16} aria-hidden="true" />Expanded ownership &amp; insider history</li>
              <li><Sparkles size={16} aria-hidden="true" />Additional screening metrics</li>
              <li><Sparkles size={16} aria-hidden="true" />First access as new data ships</li>
            </ul>
            <p className="pricing-plan__note">Not launched — a free account today gets first access automatically.</p>
          </div>
        </div>
      </section>

      <section>
        <h2>How we think about pricing</h2>
        <div className="pricing-principles">{principles.map((item) => <div key={item.title}><ShieldCheck size={18} aria-hidden="true" /><div><strong>{item.title}</strong><p>{item.body}</p></div></div>)}</div>
      </section>
    </PublicPage>
  );
}
